dependencies:
  - python>=3.8
  - numpy
  - scipy
  - pip
  - pip:
    - astropy>=4.0
    - matplotlib
    - scikit-image
    - pandas>=1.1
    - tqdm
    - photutils
    - astroquery
    - pyyaml
    - tabulate
    - imageio
    - celerite2
    - requests
    - ipython
    - jax
    - jaxlib
    - jaxopt
    - -e .